defaults:
  - _self_
  - model: jasper5
  - trainer: standard

name: null
db_root: null
use_comet: True

init_from_nemo_model:
  model:
    path: null
#    include: [""]
    exclude: ["decoder"]

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
  # in case of multiple validation sets, first one is used
    monitor: "val_map"
    mode: "max"
    save_top_k: 3
    always_save_nemo: true # saves the checkpoints as nemo files instead of PTL checkpoints
  resume_if_exists: false
  resume_ignore_no_checkpoint: false

  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
